services:
    web:
        image: getovski/bgapp-web
        deploy:
            replicas: 3
        ports:
            - 8080:80
        volumes:
            - "/home/vagrant/homework04/web:/var/www/html:ro"
        networks:
            - app-network
    db:
        image: getovski/bgapp-db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
        secrets:
           - db_root_password
secrets:
    db_root_password:
        external: true
networks:
    app-network:

